/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;

import java.io.Serializable;
import java.util.Calendar;
import javax.swing.JPanel;

/**
 *
 * @author elena
 */
public class FechaPersonalizadaPanel extends JPanel implements Serializable {

    public FechaPersonalizadaPanel() {
        initComponents();
    }

    public FechaPersonalizada getSelectedValue() {

        int hora = (Integer) horaSpinner.getValue();
        int minuto = (Integer) minutoSpinner.getValue();
        int segundo = (Integer) segundoSpinner.getValue();

        Calendar calendar = jDateChooser.getJCalendar().getCalendar();
        calendar.set(calendar.get(Calendar.YEAR),
                calendar.get(Calendar.MONTH),
                calendar.get(Calendar.DAY_OF_MONTH),
                hora, minuto, segundo);

        return new FechaPersonalizada(calendar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser = new com.toedter.calendar.JDateChooser();
        labelFecha = new javax.swing.JLabel();
        horaCompletaLabel = new javax.swing.JLabel();
        horaSpinner = new javax.swing.JSpinner();
        horaLabel = new javax.swing.JLabel();
        minutoSpinner = new javax.swing.JSpinner();
        minutoLabel = new javax.swing.JLabel();
        segundoSpinner = new javax.swing.JSpinner();
        segundoLabel = new javax.swing.JLabel();

        labelFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFecha.setText("Fecha ejecución:");

        horaCompletaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        horaCompletaLabel.setText("Hora ejecución:");

        horaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        horaLabel.setText("Hora");

        minutoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        minutoLabel.setText("Minuto");

        segundoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        segundoLabel.setText("Segundo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFecha)
                    .addComponent(horaCompletaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(horaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundoLabel))
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaCompletaLabel)
                    .addComponent(horaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaLabel)
                    .addComponent(minutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutoLabel)
                    .addComponent(segundoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoLabel))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel horaCompletaLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JSpinner horaSpinner;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel minutoLabel;
    private javax.swing.JSpinner minutoSpinner;
    private javax.swing.JLabel segundoLabel;
    private javax.swing.JSpinner segundoSpinner;
    // End of variables declaration//GEN-END:variables

}
